packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: ^4.4.3

  typescript: 5.9.2
  eslint: ^9.39.1
  "@types/node": ^22.15.3

  react: ^19.2.0
  react-dom: ^19.2.0
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
