import { config } from "@repo/eslint-config/base";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...config,
  {
    // Generated by `prisma generate` — not ours to lint.
    ignores: ["src/generated/**", "dist/**"],
  },
];
